#workflow
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Kermit
  filter:
    create: All tasks
#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eladmin?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Passw0rd12
    driver-class-name: com.mysql.jdbc.Driver
flowable:
  rest:
    app:
      authentication-mode: any-user
